---
downloads: ~/.ansible-downloads/

configure_dotfiles: false
configure_sudoers: false
configure_terminal: false
configure_iterm: false
configure_osx: false
configure_extra_packages: false
configure_jenv: false
configure_eclipse: false
configure_apachedirectorystudio: false
configure_intellij: false

dotfiles_repo: https://github.com/dhergert/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/projects/dotfiles

dotfiles_files:
  - .bash_profile
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bash-completion
  - {name: "curl", install_options: "with-libssh2"}
  - chromedriver
  - doxygen
  - gettext
  - gifsicle
  - git
  - go
  - gpg
  - hub
  - httpie
  - iperf
  - jenv
  - kubectl
  - libevent
  - sqlite
  - mcrypt
  - maven
  - mysql
  - nmap
  - node
  - nvm
  - openshift-cli
  - python
  - php
  - ssh-copy-id
  - tree
  - readline
  - openssl
  - pv
  - wget
  - wrk
  - yamllint

homebrew_uninstalled_packages:
  - cowsay

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - atlassian/tap

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - adoptopenjdk8  # https://github.com/AdoptOpenJDK/homebrew-openjdk
  - adoptopenjdk9
  - adoptopenjdk10
  - dbeaver-community
  - chromedriver
  - docker
  - dropbox
  - firefox
  - google-chrome
  - java
  - java8
  # - handbrake
  - licecap
  # - limechat
  - macvim
  - sequel-pro
  - skitch
  - slack
  # - sublime-text
  - transmit
  - vagrant

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - {id: 497799835, name: "Xcode (9.0)"}
# mas_email
# mas_password
vars_prompt:
  - name: "mas_email"
    prompt: "MAS Email"
    private: false

  - name: "mas_password"
    prompt: "MAS Password"
    private: true

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: ["lxml"]
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
